Updating naming for Conjur editions
cyberark/ansible-conjur-collection pull request #64
Opened 2021-06-17 17:05 UTC by john-odonnell

Updating naming for Conjur editions

- converts `Conjur OSS` to `Conjur Open Source`
- converts `DAP`/`Dynamic Access Provider` to `Conjur Enterprise`
- maintains `Conjur OSS Suite` and `Conjur Open Source Suite`

This is part of an automated batch of PRs across many repos listed in [cyberark/community#92](https://github.com/cyberark/community/issues/92)

2021-06-24 20:01 UTC, rpothier requested changes

2021-06-24 20:01 UTC, rpothier commented on README.md
>    v10.x+ accessible from the target node
Can we also change lines 38-40 which references DAP.

2021-06-25 14:18 UTC, john-odonnell commented on README.md
> +This collection contains components to be used with CyberArk Conjur & Conjur Enterprise
Added (formerly DAP) to the requirements listing instead of this line

2021-06-25 17:34 UTC, rpothier approved these changes
LGTM

2021-06-25 17:35 UTC, merged